---
- name: Ignore errors condition
  hosts: all 
  remote_user: ec2-user
  become: yes
  tasks:

  - name: Install a package
    ansible.builtin.yum:
     name: greens
     state: latest
    ignore_errors: yes

  - name: Install java
    ansible.builtin.yum:
     name: java
     state: latest
    ignore_errors: yes

...